### ISSUE TITLE
[REQUEST] - Foreign Only Option

### ISSUE THREAD

**Issue by ondrovic** [vagabondHustler/subsearch#422] opened 2023-05-13 22:37 UTC
**Is your feature request related to a problem? Please describe.**
Ability to download only the subtitles that are foreign only
**Describe the solution you'd like**
Adding a search option to allow for only downloading Foreign only (I know subscene.com has this option as a valid filter)

**Describe alternatives you've considered**
Downloading the foreign only manually one at a time

**Additional context**

**Comment by vagabondHustler** [comment] 2023-05-14 00:01
Sounds like a good implementation. Do you know any movies or TV shows on subscene that have 'Foreign language only ' subtitles? I'm not too familiar with that type of subtitles, so if you could suggest a few titles, it would be really helpful.

**Comment by vagabondHustler** [comment] 2023-05-17 08:25
It turns out that retrieving information specifically labeled as 'foreign parts only' from Subscene isn't as straightforward as I initially thought when scraping the HTML data. While details like language and hearing-impaired options are available, the availability of subtitles exclusively for foreign parts is not.

However, I did notice that some subtitle uploaders mention the 'foreign parts only' information in the 'Comment' section. The problem is that different uploaders may use different phrases like 'foreign parts only' or 'non-English parts,' making it unreliable.

I guess modifying the cookie could work, but to be honest, I'm not familiar with that and would need to look up how to do that.

I have not checked the other sites yet, but will.

**Comment by vagabondHustler** [comment] 2023-05-21 10:52
@ondrovic, I don't mind if it's much work. If this cookie thing isn't working for me, I think I might just implement some kind of feature where the user can define keywords like 'Foreign only,' 'Foreign parts only,' 'non-English.' Then, when scraping Subscene for subtitles, my app can check if those keywords are present in the subtitle comments. Additionally, I could include another feature where it ignores subtitle comments containing words like 'whatever,' providing the opposite effect.

Just gotta find some time to do all that :)

**Comment by vagabondHustler** [comment] 2023-06-02 13:55
This issue will be closed when PR #433 is merged. Further progress will be tracked in in Issue #434. It seems like implementing the same method for opensubtitles.org should be relatively straightforward. Unsure if it's possible to implement it for yifysubtitles.

**Closed** 2023-06-02 13:56 UTC
Labels: feature request
